name: Playwright JS

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      site: ${{ steps.mk.outputs.site }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test || true

      # (keep your artifacts if you want)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/report.html
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-results
          path: test-results/results.xml

      # Build the static site (must contain index.html at root)
      - id: mk
        name: Build site
        if: always()
        run: |
          set -eux
          mkdir -p site/runs/${{ github.run_number }}

          # Copy reports (exists only if Playwright produced them)
          [ -f playwright-report/report.html ] && cp playwright-report/report.html site/runs/${{ github.run_number }}/report.html || true
          [ -f test-results/results.xml ] && cp test-results/results.xml site/runs/${{ github.run_number }}/results.xml || true

          # Minimal index so root isn't 404
          cat > site/index.html <<'HTML'
          <!doctype html>
          <meta charset="utf-8">
          <title>Playwright Runs</title>
          <h1>Playwright Runs</h1>
          <p>Current run: <a href="runs/${{ github.run_number }}/">#${{ github.run_number }}</a></p>
          <p>Report: <a href="runs/${{ github.run_number }}/report.html">report.html</a> (if present)</p>
          <p>JUnit: <a href="runs/${{ github.run_number }}/results.xml">results.xml</a> (if present)</p>
          HTML

          echo "site=$PWD/site" >> $GITHUB_OUTPUT

      # Upload exactly ONE Pages artifact
      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.mk.outputs.site }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
