name: Playwright Tests & Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  playwright_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # --- Setup ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      
      # --- Test Execution & Report Generation ---
      # This step runs tests and automatically generates two reports:
      # 1. A **JUnit XML report** named 'results/junit.xml' (for status reporting).
      # 2. An **HTML report** in the 'playwright-report' directory (for detailed viewing).
      - name: Run Playwright tests
        run: npx playwright test --reporter=html,junit:results/junit.xml
        # The '|| true' ensures the step doesn't fail the workflow immediately 
        # if tests fail, allowing the reporting steps to run.
        continue-on-error: true 
        # OR: run: npx playwright test; exit 0 
      
      # --- Reporting: Summary in PR/Workflow Run ---
      # This action processes the JUnit XML file and posts a summary directly 
      # to the workflow run page and (optionally) as a comment in a PR.
      - name: Publish JUnit XML Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Playwright Test Results
          path: results/junit.xml # Path to the JUnit file generated above
          reporter: jest-junit # Format of the report
          fail-on-error: true
          
      # --- Artifact Upload: HTML Report ---
      # Uploads the self-contained HTML report directory for download and viewing.
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-html-report
          path: playwright-report/
          retention-days: 5
          
      # --- Artifact Upload: Screenshots/Videos (Optional) ---
      # If your tests generate any screenshots or videos on failure, upload them too.
      - name: Upload test results (videos/screenshots)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-artifacts
          path: test-results/
          retention-days: 5
