name: Playwright – HTML & JUnit reports

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Run tests with reporters:
      # - junit  -> creates ./results.xml (default filename)
      # - html   -> creates ./playwright-report/ (with report.html)
      - name: Run Playwright (HTML + JUnit)
        run: |
          set -eux
          npx playwright test --reporter=junit,html
          # Normalize junit location to ./test-results/results.xml
          mkdir -p test-results
          if [ -f results.xml ]; then
            mv results.xml test-results/results.xml
          fi

      # (Optional) Show what was produced (helps when debugging)
      - name: List generated reports
        if: always()
        run: |
          echo "== test-results =="
          find test-results -type f -maxdepth 2 -print || true
          echo "== playwright-report =="
          find playwright-report -type f -maxdepth 2 -print || true

      # Upload JUnit XML
      - name: Upload JUnit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results/results.xml
          if-no-files-found: error

      # Upload the full HTML report folder (contains report.html + assets)
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: error
